### ISSUE TITLE
License says Apache, pom says GPLc2

### ISSUE THREAD

**Issue by ghost** [benstadin/spatialite4-jdbc#8]
Which should I believe... as far as the jar is concerned, it ends up saying GPLv2 internally and this is an issue for the company I work for.

![Screen Shot 2019-04-25 at 3 30 48 PM](https://user-images.githubusercontent.com/1952419/56762987-32091e80-676f-11e9-8e54-45fc6b88ed5c.png)

**Comment by benstadin** [comment]
Thanks for reporting. I fixed the pom file to use Apache license, and I've double checked that change with the originate repositories used by this project.

**Comment by ghost** [comment]
Thanks for clarifying and updating !

The quick response is much appreciated.
